spring:
  cloud:
    nacos:
      discovery:
        server-addr: casual.ink:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://casual.ink:3306/blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: WzhmkWSm3Qh/gNHbDo/iXNqI6VWiylJ+NTvsiuMJKpIXhcMjhThxeGSDRANTKOzupPIKdR44N0ec0NCLGBEjsQ==
    druid:
      connectionProperties: config.decrypt=true
  rabbitmq:
    password: guest
    port: 5672
    host: casual.ink
    username: guest
  redis:
    database: 0
    port: 6379
    host: casual.ink
    lettuce:
      pool:
        max-idle: 8
        min-idle: 3
        max-active: 8
        max-wait: -1s
    timeout: 5000s
  data:
    mongodb:
      database: blog
      port: 27017
      host: casual.ink
      username: lwt
      password: 123456
