spring:
  cloud:
    nacos:
      discovery:
        server-addr: casual.ink:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://casual.ink:3306/blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    druid:
      username: root
      password: MMLzV3uM+a1eQK8lRnW8YoQk3Lkq8KIavGMBhbHh7XXQjhhcDU4/ePeJ+lq5jxNZNcqOwR4CzjjEMe/BwkStQg==
      connect-properties: {config.decrypt: true,config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJQo2CqjYDpFvpWeHIOQqdli5eNG1F2qUpJpKUxFOHQ7Y7TZhlKCv50tYGMmXMiIaupzM6K/PyDiPQ5CMf8DK7kCAwEAAQ==}
      filters: config
  rabbitmq:
    password: guest
    port: 5672
    host: casual.ink
    username: guest
  redis:
    database: 0
    port: 9736
    host: casual.ink
    lettuce:
      pool:
        max-idle: 8
        min-idle: 3
        max-active: 8
  data:
    mongodb:
      database: blog
      port: 27017
      host: casual.ink
      username: lwt
      password: 123456
logging:
  path: E:/logs/blog-user