spring:
  application:
    name: blog-index
  profiles:
    active: @profileActive@
  thymeleaf:
    cache: false
    prefix: classpath:/static/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
server:
  port: 81