spring:
  application:
    name: blog-index
  profiles:
    active: @profileActive@
    include: common
  thymeleaf:
    cache: false
    prefix: classpath:/static/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
server:
  port: 81
logging:
  level: {ink.casual.common.mapper: debug}
  file:
    max-history: 7